# Generated by Django 4.2.9 on 2024-07-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jeans',
            options={'verbose_name': 'ДЖИНСИ'},
        ),
    ]
